version: '3'
services:
  users_db:
      image: mysql:5.6
      restart: always
      volumes:
        - ./db_data:/docker-entrypoint-initdb.d
      environment:
        MYSQL_ROOT_PASSWORD: 'root'
        MYSQL_DATABASE: 'users'
        MYSQL_USER: 'user'
        MYSQL_PASSWORD: 'root'
      healthcheck:
        test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
        timeout: 20s
        retries: 10
  users-api:
    build:
      context: .
    ports:
      - 3070:3070
    volumes:
      - ".:/opt/app/"
    depends_on:
      - users_db
    links:
      - users_db
    command: npm run start:server